Vagrant.configure("2") do |config|
 
  config.vm.provision "docker"
 
  # The following line terminates all ssh connections. Therefore
  # Vagrant will be forced to reconnect.
  # That's a workaround to have the docker command in the PATH
  config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
 
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "pex-dockerhost"
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.network "forwarded_port", guest: 5672, host: 5672
  config.vm.network "forwarded_port", guest: 15672, host: 15672
 
  config.vm.provider :virtualbox do |vb|
      vb.name = "pex-dockerhost"
      vb.gui = false
      vb.memory = 4096
      vb.cpus = 2
  end

  # Disable synced folders (prevents an NFS error on "vagrant up")
  config.vm.synced_folder ".", "/vagrant", disabled: true
end